@CityInfoAPI.Web_HostAddress = https://localhost:7024
// variables
@schema=https
@hostname=localhost
@port=7024
@version=2.0
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkpvaG4iLCJmYW1pbHlfbmFtZSI6IkRvZSIsImNpdHkiOiJSaWNobW9uZCIsIm5iZiI6MTc0MTExNzExOCwiZXhwIjoxNzQxMTE4OTE4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDI0IiwiYXVkIjoiQ2l0eUluZm9BUEkifQ.I5XKSSQSxb9mf7qXR_zZhl-ESt2Cq9OIYzSNdEjG2jA
@cityGuid=38276231-1918-452d-a3e9-6f50873a95d2
@pointGuid=b50b9894-9195-4cb4-88dc-b3b0cbe796bd

// get token
POST {{schema}}://{{hostname}}:{{port}}/api/v1.0/authentication/authenticate
Content-Type: application/json

{
  "UserName": "a",
  "Password": "b"
}
###


// CITIES - all with params
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities?pageNumber=1&pageSize=10
Accept: application/json
Authorization: Bearer {{token}}
###

// CITIES - all, xml
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities
Accept: application/xml
Authorization: Bearer {{token}}
###

// CITY by GUID
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}
Accept: application/json
Authorization: Bearer {{token}}
###


// CITY by GUID xml
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}
Accept: application/xml
Authorization: Bearer {{token}}
###

// CITY by GUID w/o points of interest
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}?includePointsOfInterest=false
Accept: application/json
Authorization: Bearer {{token}}
###

// CITY by GUID w/o points of interest xml
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}?includePointsOfInterest=false
Accept: application/xml
Authorization: Bearer {{token}}
###

// CITY - create
POST {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "CITY Test new http",
  "description": "CITY Test new http"
}
###

// CITY - update
PUT {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "CITY Test updated http",
  "description": "CITY Test updated http"
}
###

// CITY - patch
PATCH {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}
Content-Type: application/json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/name",
        "value": "CITY Test http Patched"
    },
    {
        "op": "replace",
        "path": "/description",
        "value": "description http patched"
    }
]
###

// CITY - delete
DELETE {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}
Authorization: Bearer {{token}}
###



// POINTS OF INTEREST - for a city, json
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Authorization: Bearer {{token}}
Accept: application/json
###

// POINTS OF INTEREST - for a city, xml
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Authorization: Bearer {{token}}
Accept: application/xml
###

// POINTS OF INTEREST by Guid, json
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest/{{pointGuid}}
Authorization: Bearer {{token}}
Accept: application/json
###

// POINTS OF INTEREST by Guid, xml
GET {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest/{{pointGuid}}
Authorization: Bearer {{token}}
Accept: application/xml
###

// POINTS OF INTEREST - create, json
POST {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "cityGuid": "38276231-1918-452d-a3e9-6f50873a95d2",
  "name": "POI Test 2",
  "description": "POI Test 2"
}
###

// POINTS OF INTEREST - create, xml
POST {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Content-Type: application/json
Accept: application/xml
Authorization: Bearer {{token}}

{
  "cityGuid": "38276231-1918-452d-a3e9-6f50873a95d2",
  "name": "POI Test 3",
  "description": "POI Test 3"
}
###

// POINTS OF INTEREST - update, json
PUT {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "cityGuid": "38276231-1918-452d-a3e9-6f50873a95d2",
  "name": "POI Test 3 Update",
  "description": "POI Test 3 Update"
}
###

// POINTS OF INTEREST - update, xml
PUT {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest
Content-Type: application/json
Accept: application/xml
Authorization: Bearer {{token}}

{
  "cityGuid": "38276231-1918-452d-a3e9-6f50873a95d2",
  "name": "POI Test 3 Update xml",
  "description": "POI Test 3 Update xml"
}
###

// POINTS OF INTEREST - patch, json
PATCH {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest/{{pointGuid}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/name",
        "value": "POI Test 3 Patched"
    },
    {
        "op": "replace",
        "path": "/description",
        "value": "POI Test 3 description Patched"
    }
]
###

// POINTS OF INTEREST - patch, xml
PATCH {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest/{{pointGuid}}
Content-Type: application/json
Accept: application/xml
Authorization: Bearer {{token}}

[
    {
        "op": "replace",
        "path": "/name",
        "value": "POI Test 3 Patched xml"
    },
    {
        "op": "replace",
        "path": "/description",
        "value": "POI Test 3 description Patched xml"
    }
]
###

// POINTS OF INTEREST - delete
DELETE {{schema}}://{{hostname}}:{{port}}/api/v{{version}}/cities/{{cityGuid}}/pointsofinterest/{{pointGuid}}
Authorization: Bearer {{token}}
###
